import { userDataTypes, orderListUserTypes } from "@/types/components";

export const usersData: userDataTypes[] = [
  {
    id: 1,
    name: "hello world",
    avatarSrc:
      "https://images.unsplash.com/photo-1533738363-b7f9aef128ce?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1935&q=80",
    isOnline: true,
    isActive: false,
    lastSeen: "29 mar",
  },
  {
    id: 2,
    name: "welcome world",
    avatarSrc:
      "https://images.unsplash.com/photo-1507146426996-ef05306b995a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80",
    isOnline: true,
    isActive: false,
    lastSeen: "29 mar",
  },
  {
    id: 3,
    name: "amazing world",
    avatarSrc:
      "https://images.unsplash.com/photo-1563889362352-b0492c224f62?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGh1c2t5JTIwcHVwcHl8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60",
    isOnline: true,
    isActive: true,
    lastSeen: "29 mar",
  },
  {
    id: 4,
    name: "fantastic world",
    avatarSrc:
      "https://images.unsplash.com/photo-1589656966895-2f33e7653819?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8YW5pbWFsc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60",
    isOnline: true,
    isActive: true,
    lastSeen: "29 mar",
  },
  {
    id: 5,
    name: "what a world",
    avatarSrc:
      "https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8YW5pbWFsc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60",
    isOnline: false,
    isActive: false,
    lastSeen: "29 mar",
  },
  {
    id: 6,
    name: "this is world",
    avatarSrc:
      "https://images.unsplash.com/photo-1574068468668-a05a11f871da?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8YW5pbWFsc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60",
    isOnline: false,
    isActive: true,
    lastSeen: "29 mar",
  },
  {
    id: 7,
    name: "uff oh! world",
    avatarSrc:
      "https://images.unsplash.com/photo-1493916665398-143bdeabe500?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fGFuaW1hbHN8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60",
    isOnline: false,
    isActive: true,
    lastSeen: "29 mar",
  },

  {
    id: 8,
    name: "nice world",
    avatarSrc:
      "https://images.unsplash.com/photo-1535083783855-76ae62b2914e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGFuaW1hbHN8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60",
    isOnline: false,
    isActive: true,
    lastSeen: "29 mar",
  },
];

export const OrderlistUsers: orderListUserTypes[] = [
  {
    id: 0,
    name: "Tony Briggs",
    phone: "8927384728",
    email: "tonybriggs@gmail.com",
    location: "Rukpokwu Portharcourt",
    IdNumber: "#435fre",
    date: "JUN 23, 2023",
    amount: 2300,
    payment: true,
    products: [
      {
        id: 1,
        name: "Biscuits",
        productId: "#435fre",
        quantity: 50,
        price: 60,
      },
      {
        id: 2,
        name: "Potato Chips",
        productId: "#435fre",
        quantity: 30,
        price: 30,
      },
      {
        id: 3,
        name: "Coca-cola bottle",
        productId: "#435fre",
        quantity: 500,
        price: 2000,
      },
      {
        id: 4,
        name: "Chocolate cake",
        productId: "#435fre",
        quantity: 10,
        price: 300,
      },
      {
        id: 5,
        name: "Milk cake",
        productId: "#435fre",
        quantity: 20,
        price: 600,
      },
      {
        id: 6,
        name: "Bread",
        productId: "#435fre",
        quantity: 40,
        price: 100,
      },
    ],
  },
  {
    id: 1,
    name: "Shunko Ekun",
    phone: "8927384729",
    email: "shunkoekun@gmail.com",
    location: "Nembe Junction",
    IdNumber: "#9053uy",
    amount: 5000,
    date: "SEP 4, 2022",
    payment: false,
    products: [
      {
        id: 1,
        name: "Biscuits",
        productId: "#435fre",
        quantity: 50,
        price: 60,
      },
      {
        id: 2,
        name: "Potato Chips",
        productId: "#435fre",
        quantity: 30,
        price: 30,
      },
      {
        id: 3,
        name: "Coca-cola bottle",
        productId: "#435fre",
        quantity: 500,
        price: 2000,
      },
    ],
  },
  {
    id: 2,
    name: "Obi Akpan",
    phone: "8927384730",
    email: "obiakpan@gmail.com",
    location: "Obedi Oki",
    IdNumber: "#08eu7d",
    amount: 6000,
    date: "SEP 10, 2022",
    payment: false,
    products: [
      {
        id: 1,
        name: "Biscuits",
        productId: "#435fre",
        quantity: 50,
        price: 60,
      },
      {
        id: 2,
        name: "Potato Chips",
        productId: "#435fre",
        quantity: 30,
        price: 30,
      },
      {
        id: 3,
        name: "Coca-cola bottle",
        productId: "#435fre",
        quantity: 500,
        price: 2000,
      },
      {
        id: 4,
        name: "Chocolate cake",
        productId: "#435fre",
        quantity: 10,
        price: 300,
      },
      {
        id: 5,
        name: "Milk cake",
        productId: "#435fre",
        quantity: 20,
        price: 600,
      },
    ],
  },
  {
    id: 3,
    name: "Olamide Obinna",
    phone: "8927384731",
    email: "olamideobinna@gmail.com",
    location: "Lagos",
    IdNumber: "#9deje67",
    amount: 2300,
    date: "JUL 3, 2020",
    payment: true,
    products: [
      {
        id: 1,
        name: "Biscuits",
        productId: "#435fre",
        quantity: 50,
        price: 60,
      },
      {
        id: 2,
        name: "Potato Chips",
        quantity: 30,
        productId: "#435fre",
        price: 30,
      },
      {
        id: 3,
        name: "Coca-cola bottle",
        quantity: 500,
        productId: "#435fre",
        price: 2000,
      },
      {
        id: 4,
        name: "Chocolate cake",
        quantity: 10,
        productId: "#435fre",
        price: 300,
      },
    ],
  },
  {
    id: 4,
    name: "Fatima Ngozi",
    phone: "8927384732",
    email: "fatimangozi@gmail.com",
    location: "Lafia debe",
    IdNumber: "#83ud8e",
    amount: 3300,
    date: "JUL 12, 2019",
    payment: false,
    products: [
      {
        id: 1,
        name: "Biscuits",
        quantity: 50,
        price: 60,
        productId: "#435fre",
      },
      {
        id: 2,
        name: "Potato Chips",
        productId: "#435fre",
        quantity: 30,
        price: 30,
      },
      {
        id: 3,
        name: "Coca-cola bottle",
        productId: "#435fre",
        quantity: 500,
        price: 2000,
      },
      {
        id: 4,
        name: "Chocolate cake",
        productId: "#435fre",
        quantity: 10,
        price: 300,
      },
      {
        id: 5,
        name: "Milk cake",
        productId: "#435fre",
        quantity: 20,
        price: 600,
      },
      {
        id: 6,
        name: "Bread",
        productId: "#435fre",
        quantity: 40,
        price: 100,
      },
      {
        id: 7,
        name: "Can coke",
        productId: "#435fre",
        quantity: 60,
        price: 700,
      },
      {
        id: 8,
        name: "Milk bottle",
        productId: "#435fre",
        quantity: 90,
        price: 3000,
      },
    ],
  },
  {
    id: 5,
    name: "Gbemi Degema",
    phone: "8927384733",
    email: "gbemidegema@gmail.com",
    location: "Ketu jabu",
    IdNumber: "#ru68ku",
    amount: 6969,
    date: "JUN 23, 2019",
    payment: true,
    products: [
      {
        id: 1,
        name: "Biscuits",
        productId: "#435fre",
        quantity: 50,
        price: 60,
      },
      {
        id: 2,
        name: "Potato Chips",
        productId: "#435fre",
        quantity: 30,
        price: 30,
      },
      {
        id: 3,
        name: "Coca-cola bottle",
        quantity: 500,
        productId: "#435fre",
        price: 2000,
      },
      {
        id: 4,
        name: "Chocolate cake",
        productId: "#435fre",
        quantity: 10,
        price: 300,
      },
      {
        id: 5,
        productId: "#435fre",
        name: "Milk cake",
        quantity: 20,
        price: 600,
      },
      {
        id: 6,
        name: "Bread",
        productId: "#435fre",
        quantity: 40,
        price: 100,
      },
      {
        id: 7,
        name: "Can coke",
        productId: "#435fre",
        quantity: 60,
        price: 700,
      },
      {
        id: 8,
        name: "Milk bottle",
        productId: "#435fre",
        quantity: 90,
        price: 3000,
      },
      {
        id: 9,
        name: "Chocolate Ice-cream",
        productId: "#435fre",
        quantity: 20,
        price: 50,
      },
      {
        id: 10,
        name: "Marshmallo packets",
        productId: "#435fre",
        quantity: 10,
        price: 100,
      },
    ],
  },
];
