export {default as ProductCategory} from './ProductCategory'
export {default as ProductImages} from './ProductImages'
export {default as ProductInventory} from './ProductInventory'
export {default as Regions} from './Regions'
export {default as ProductDescription} from './ProductDescription'
export {default as ProductPricing} from './ProductPricing'
export {default as ProductShipping} from './ProductShipping'
export {default as FileUpload} from './FileUpload'